/*
 * This source file was generated by the Gradle 'init' task
 */
package dws.labs;

import java.util.concurrent.TimeUnit;

import com.beust.jcommander.JCommander;

import dws.labs.lunch.Lunch;

public class App {
    public static void main(String... args) throws InterruptedException {
        var parsedArgs = new CommandLineArgs();

        JCommander.newBuilder()
                .addObject(parsedArgs)
                .build()
                .parse(args);

        var lunch = new Lunch(
                parsedArgs.getProgrammersNum(),
                parsedArgs.getWaitersNum(),
                parsedArgs.getSoupAmount());

        lunch.run(parsedArgs.getTimeout(), TimeUnit.MILLISECONDS);
    }
}
