/*
 * This source file was generated by the Gradle 'init' task
 */
package dws.labs.lunch;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.FieldSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;

class LunchTest {
    @DisplayName("Programmer's lunch test")
    @ParameterizedTest(name = "Programmers: {0}, each programmer needs {1} portions of soup")
    @FieldSource
    void test(int programmersNum, int needSoup) throws InterruptedException {
        var lunch = new Lunch(programmersNum, programmersNum * needSoup, needSoup);

        assertTrue(lunch.run(2, TimeUnit.SECONDS));
    }

    static List<Arguments> test = Arrays.asList(
            Arguments.of(3, 5),
            Arguments.of(5, 10),
            Arguments.of(5, 15),
            Arguments.of(10, 10));
}
